version: "3"

services:

  flask:
    build: ./app
    container_name: flask
    restart: always
    environment:
      - APP_NAME=AIJB
    expose:
      - 8080
    # ports: 
    #   - "80:80"

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"